#!/usr/bin/python -Wall
# -*- coding: utf-8 -*-
"""
<div id="content">
<div style="text-align:center;" class="print"><img src="images/print_page_logo.png" alt="projecteuler.net" style="border:none;" /></div>
<h2>Triangular, pentagonal, and hexagonal</h2><div id="problem_info" class="info"><h3>Problem 45</h3><span>Published on Friday, 6th June 2003, 06:00 pm; Solved by 44229; Difficulty rating: 5%</span></div>
<div class="problem_content" role="problem">
<p>Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:</p>
<table>
<tr>
<td>Triangle</td>
<td>&nbsp;</td>
<td>T<sub><i>n</i></sub>=<i>n</i>(<i>n</i>+1)/2</td>
<td>&nbsp;</td>
<td>1, 3, 6, 10, 15, ...</td>
</tr>
<tr>
<td>Pentagonal</td>
<td>&nbsp;</td>
<td>P<sub><i>n</i></sub>=<i>n</i>(3<i>n</i>&minus;1)/2</td>
<td>&nbsp;</td>
<td>1, 5, 12, 22, 35, ...</td>
</tr>
<tr>
<td>Hexagonal</td>
<td>&nbsp;</td>
<td>H<sub><i>n</i></sub>=<i>n</i>(2<i>n</i>&minus;1)</td>
<td>&nbsp;</td>
<td>1, 6, 15, 28, 45, ...</td>
</tr>
</table>
<p>It can be verified that T<sub>285</sub> = P<sub>165</sub> = H<sub>143</sub> = 40755.</p>
<p>Find the next triangle number that is also pentagonal and hexagonal.</p>
</div><br />
<br /></div>
"""

def Triangle(n):
    return (n*(n+1))/2

def Pentagonal(n):
    return (n*(3*n-1))/2

def Hexagonal(n):
    return n*(2*n-1)

MAX_LIMIT = 100000

for i in range(285, MAX_LIMIT):
    ret_i = Triangle(i)
    for j in range(100, i):
        if ret_i != Pentagonal(j):
            continue

        for k in range(100, j):
            if ret_i == Hexagonal(k):
                print i, j, k, ret_i
                exit(0)

