#!/usr/bin/python -Wall
# -*- coding: utf-8 -*-
"""
<div id="content">
<div style="text-align:center;" class="print"><img src="images/print_page_logo.png" alt="projecteuler.net" style="border:none;" /></div>
<h2>Pentagon numbers</h2><div id="problem_info" class="info"><h3>Problem 44</h3><span>Published on Friday, 23rd May 2003, 06:00 pm; Solved by 33755; Difficulty rating: 5%</span></div>
<div class="problem_content" role="problem">
<p>Pentagonal numbers are generated by the formula, P<sub><var>n</var></sub>=<var>n</var>(3<var>n</var>&minus;1)/2. The first ten pentagonal numbers are:</p>
<p style="text-align:center;">1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...</p>
<p>It can be seen that P<sub>4</sub> + P<sub>7</sub> = 22 + 70 = 92 = P<sub>8</sub>. However, their difference, 70 &minus; 22 = 48, is not pentagonal.</p>
<p>Find the pair of pentagonal numbers, P<sub><var>j</var></sub> and P<sub><var>k</var></sub>, for which their sum and difference are pentagonal and D = |P<sub><var>k</var></sub> &minus; P<sub><var>j</var></sub>| is minimised; what is the value of D?</p>
</div><br />
<br /></div>
"""

from math import sqrt

MAX_LIMIT = 100000

def calc_pentagonal(num):
    return (num * (3 * num - 1))/2

def is_pentagonal(num):
    temp = 1 + (4 * 3 * 2 * num)
    check = sqrt(temp) + 1
    if check % 6 == 0:
        return True
    else:
        return False

def do_calc():
    #global pen
    #init()
    for i in range (1, MAX_LIMIT):
        for j in range (i+1, MAX_LIMIT):
            Pa = calc_pentagonal(i) + calc_pentagonal(j)
            if (is_pentagonal(Pa) == True):
                Pb = abs(calc_pentagonal(i) - calc_pentagonal(j))
                #print Pa, Pb
                if (is_pentagonal(Pb) == True):
                    print "found (+)",Pb, "(-)",Pa, "i=",calc_pentagonal(i), "j=",calc_pentagonal(j), "result=", abs(calc_pentagonal(i)-calc_pentagonal(j))
                    return 0

do_calc()
